### ISSUE TITLE
Provide a utility to combine data providers

### ISSUE THREAD

**Issue by theofidry** [ergebnis/data-provider#123]
The actual README example already show a problem:

```php
    /**
     * @dataProvider \Ergebnis\DataProvider\StringProvider::blank()
     * @dataProvider \Ergebnis\DataProvider\StringProvider::empty()
     */
```

If there is a conflicting key, the a set will be silently overridden. Maybe this will change in future PHP 10+ version, but this is not soon and will not change for the current versions. For this reason, I tend to take the habit of enforcing one and only one data provider, but that can combine others:

```php
public static function myNewProvider(): iterable
{
    yield from StringProvider::blank();
    yield from StringProvider::empty();
}
```

In this case, if there is a conflict, then PHPUnit will tell you about it.

Now often I use this as well to separate more clearly some data providers or re-use them. I that situation I like to prefix all the entries coming from a provider with something, e.g. :

```php
public static function myNewProvider(): iterable
{
    foreach (StringProvider::blank() as $label => $set) {
        yield '[blank] '.$label => $set;
    }

    foreach (StringProvider::empty() as $label => $set) {
        yield '[empty] '.$label => $set;
    }
}
```

It works, but a bit verbose and less elegant. Instead, we could have something along the lines of:

```php
public static function myNewProvider(): iterable
{
    yield from DataProviderPrefixer::prefix('[blank]', StringProvider::blank());
    yield from DataProviderPrefixer::prefix('[empty]', StringProvider::empty());
}
```

WDYT?

**Comment by danon** [comment]
Might check out https://github.com/T-Regx/CrossDataProviders
